# Use an official Miniconda image as the base
FROM continuumio/miniconda3

# Set the working directory in the container
WORKDIR /app

# Install git and make
RUN apt-get update && apt-get install -y git make

# Clone the GitHub repository when building the container
RUN git clone https://github.com/ARKNravi/MLOps-Make-File.git .

# Install dependencies from environment.yml
RUN conda env create -f environment.yml || conda env update -f environment.yml

# Make RUN commands use the new environment
SHELL ["conda", "run", "-n", "mlops-makefile", "/bin/bash", "-c"]

# Use the cloned entrypoint.sh and ensure it's executable
RUN chmod +x entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["./entrypoint.sh"]
