# Use an official Miniconda image as the base
FROM continuumio/miniconda3

# Set the working directory in the container
WORKDIR /app

# Install git and make
RUN apt-get update && apt-get install -y git make

# Clone the GitHub repository if it doesn't exist, otherwise pull the latest changes
RUN git clone https://github.com/ARKNravi/MLOps-Make-File.git . || git pull

# Check if environment exists before creating
RUN conda env list | grep mlops-makefile || conda env create -f environment.yml || conda env update -f environment.yml

# Make RUN commands use the new environment
SHELL ["conda", "run", "-n", "mlops-makefile", "/bin/bash", "-c"]

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/entrypoint.sh"]