version: "3"
services:
  mlops-app:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=sqlite:////app/mlflow.db  # Use four slashes for absolute path
    command: ["/entrypoint.sh"]
  
  mlflow:
    image: continuumio/miniconda3  # Use Miniconda or a base image that has Conda
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - MLFLOW_TRACKING_URI=sqlite:////app/mlflow.db
    command: mlflow ui --backend-store-uri sqlite:///mlflow.db --host 0.0.0.0 --port 5000
