version: "3"
services:
    mlops-app:
        build: .
        ports:
            - "7000:5000"
        environment:
            - MLFLOW_TRACKING_URI=sqlite:////app/mlflow.db
        network_mode: "host"  # Use host network mode