version: "3"
services:
    mlops-app:
        build: .
        ports:
            - "6000:6000"  # Change the port mapping to 6000
        environment:
            - MLFLOW_TRACKING_URI=sqlite:////app/mlflow.db
