version: "3"
services:
    mlops-app:
        build: .
        ports:
            - "6000:6000"  # Ensure port 6000 is correctly mapped
        environment:
            - MLFLOW_TRACKING_URI=sqlite:////app/mlflow.db
        expose:
            - "6000"  # Optional: explicitly expose port 6000
