# Use an official Miniconda image as the base
FROM continuumio/miniconda3

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y git make

# Clone or pull the repository based on whether it exists
RUN if [ -d ".git" ]; then \
        echo "Repository already exists. Pulling the latest changes..."; \
        git -C . pull; \
    else \
        echo "Cloning repository..."; \
        git clone https://github.com/ARKNravi/MLOps-Make-File.git .; \
    fi

# Check if the environment exists; if not, create it
RUN conda env list | grep mlops-makefile || conda env create -f environment.yml

# Activate the Conda environment, run make all, and start MLflow on port 6000
CMD ["bash", "-c", "\
    source activate mlops-makefile && \
    cd /app && \
    make mlflow_server && \
    port=6000; \
    while lsof -i :$port; do \
        echo Port $port is in use. Trying the next port...; \
        port=$((port + 1)); \
    done; \
    echo Using port $port; \
    # Run MLflow UI on the available port \
    mlflow ui --backend-store-uri sqlite:///mlflow.db --host 0.0.0.0 --port $port"]
