version: "3"
services:
    mlops-app:
        build: .
        ports:
            - "127.0.0.1:6000:6000"  # Bind to localhost on port 6000
        environment:
            - MLFLOW_TRACKING_URI=sqlite:////app/mlflow.db
        expose:
            - "6000"  # Optional: explicitly expose port 6000
