version: "3"
services:
    mlops-app:
        build: .
        ports:
            - "5000:5000" # Map port 5000 only. The Dockerfile will dynamically change the exposed port if needed.
        environment:
            - MLFLOW_TRACKING_URI=sqlite:////app/mlflow.db
