version: "3"
services:
    mlops-app:
        build: .
        ports:
            - "7000:7000" # Map container port 7000 to host port 7000
        environment:
            - MLFLOW_TRACKING_URI=sqlite:////app/mlflow.db
